apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: postgresql
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
    - postgresql
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
